call plug#begin('~/.vim/plugged')

" Appearance customize
Plug 'mhinz/vim-startify'                       " customize the startup page
Plug 'glepnir/oceanic-material'                 " theme
Plug 'itchyny/lightline.vim'                    " define the status-bar
Plug 'mengelbrecht/lightline-bufferline'
Plug 'ryanoasis/vim-devicons'
Plug 'kristijanhusak/defx-icons'

" Plug for base input
Plug 'jiangmiao/auto-pairs'                     " auto pair bracket when input
Plug 'neoclide/coc.nvim', {'branch': 'release'} " auto complete
Plug 'andymass/vim-matchup'                     " make '%' support more feature
Plug 'voldikss/vim-translator'                  " select block and enter Translate*
Plug 'junegunn/vim-easy-align'                  " select block and enter 'ga[align-char]' to align by special char
Plug 'easymotion/vim-easymotion'                " use <leader><leader> to active plugin, use w/f to use more powerful function 
Plug 'kevinoid/vim-jsonc'
Plug 'terrortylor/nvim-comment'

" Plug for html
Plug 'mattn/emmet-vim'
Plug 'alvan/vim-closetag'

" plug for vue
Plug 'posva/vim-vue'
Plug 'ThePrimeagen/vim-be-good'

" plug for markdown
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
let g:vim_markdown_fenced_languages = ['css', 'java', 'javascript', 'js=javascript', 'sass', 'xml', 'typescrtpt', 'ts=typescrtpt']

" plug for dir_tree
if has('nvim')
  Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' } " use F3 to toggle dir_tree, hjkl to move, n(new), d(delete)
else
  Plug 'Shougo/defx.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif

" Plug for git
Plug 'kdheepak/lazygit.nvim', { 'branch': 'nvim-v0.4.3' }
nnoremap <silent> <leader>lg :LazyGit<CR>
Plug 'airblade/vim-gitgutter' " show git changes in line-number bar, [c or ]c(jump to privious or next change), <leader>hp(prview change),  <leader>hu(undo change)

call plug#end()

" enable vim matchup
let g:loaded_matchit = 1

let g:VIM_SCRIPT_PATH = '~/.vim/'
call helpers#source_dir(VIM_SCRIPT_PATH . './plugins')

