call plug#begin('~/.vim/plugged')

Plug 'mhinz/vim-startify'
Plug 'jiangmiao/auto-pairs'  "auto pair bracket when input
Plug 'neoclide/coc.nvim', {'branch': 'release'}  "auto complete
Plug 'andymass/vim-matchup'
Plug 'glepnir/oceanic-material'
Plug 'voldikss/vim-translator'

" plug for base input
Plug 'junegunn/vim-easy-align'

" plug for status bar
Plug 'itchyny/lightline.vim'
Plug 'mengelbrecht/lightline-bufferline'
Plug 'itchyny/vim-gitbranch'

Plug 'easymotion/vim-easymotion'

" plug for html
Plug 'mattn/emmet-vim'
Plug 'alvan/vim-closetag'

" plug for vue
Plug 'posva/vim-vue'

Plug 'ThePrimeagen/vim-be-good'

" plug for markdown
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
let g:vim_markdown_fenced_languages = ['css', 'java', 'javascript', 'js=javascript', 'sass', 'xml', 'typescrtpt', 'ts=typescrtpt']

" plug for dir_tree
if has('nvim')
  Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/defx.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif

call plug#end()

" enable vim matchup
let g:loaded_matchit = 1

" remap default leader for emmet-vim
let g:user_emmet_leader_key='<C-Z>'

let g:VIM_SCRIPT_PATH = '~/.vim/'
call helpers#source_dir(VIM_SCRIPT_PATH . './plugins')

