
nnoremap <SPACE> <Nop>
let mapleader=" "

call plug#begin('~/.vim/plugged')
Plug 'mhinz/vim-startify'
Plug 'jiangmiao/auto-pairs'
Plug 'glepnir/oceanic-material'
Plug 'itchyny/lightline.vim'
Plug 'mengelbrecht/lightline-bufferline'
Plug 'easymotion/vim-easymotion'

if has('nvim')
	Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' }
else
	Plug 'Shougo/defx.nvim'
	Plug 'roxma/nvim-yarp'
	Plug 'roxma/vim-hug-neovim-rpc'
endif

call plug#end()

"autocmd vimenter * colorscheme gruvbox
"Plug 'morhetz/gruvbox'

set background=dark
colorscheme oceanic_material

" enable ruler
set ruler
set laststatus=2

set nu
"set fdm=indent " set default fold model as indent
set clipboard=unnamed,unnamedplus "use system clipboard
set cursorline
syntax enable                           " use syntax highlighting

set encoding=utf-8                      " configure the encoding
set fileencoding=utf-8
set mouse=a

set tabstop=2                           " Insert 2 spaces for a tab
set softtabstop=-1                      " Automatically keeps in sync with shiftwidth
set shiftwidth=2                        " Change the number of space characters inserted for indentation
set smarttab                            " Makes tabbing smarter will realize you have 2 vs 4
set expandtab                           " Converts tabs to spaces
set smartindent                         " Makes indenting smart

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
noremap <silent> <F3> :Defx <CR>

call defx#custom#option('_', {
      \ 'winwidth': 40,
      \ 'split': 'vertical',
      \ 'direction': 'topleft',
      \ 'show_ignored_files': 0,
      \ 'buffer_name': '',
      \ 'toggle': 1,
      \ 'resume': 1
      \ })

