export HOMEBREW_NO_AUTO_UPDATE=true
alias vim=nvim

if [ -z "$TMUX" ]
then
    tmux attach -t Gaarahan || tmux new -s Gaarahan
fi
# export PATH="/usr/local/opt/icu4c/bin:$PATH"
# export PATH="/usr/local/opt/icu4c/sbin:$PATH"

PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" # for macos use realpath command

bindkey -v # use vim mode
plugins=(
  vi-mode
)

# Remove mode switching delay.
KEYTIMEOUT=5

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
    [[ $1 = 'block' ]]; then
          echo -ne '\e[1 q'

        elif [[ ${KEYMAP} == main ]] ||
          [[ ${KEYMAP} == viins ]] ||
          [[ ${KEYMAP} = '' ]] ||
          [[ $1 = 'beam' ]]; then
                      echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select

# Use beam shape cursor on startup.
echo -ne '\e[5 q'

# fix cursor in vi mode
_fix_cursor() {
  echo -ne '\e[5 q'
}
precmd_functions+=(_fix_cursor)

bindkey -s "^G" "lazygit\n"

stty eof undef  # prevent C-d to close panel

# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

source /usr/share/nvm/init-nvm.sh
