export HOMEBREW_NO_AUTO_UPDATE=true
alias vim=nvim

if [ -z "$TMUX" ]
then
    tmux attach -t Gaarahan || tmux new -s Gaarahan
fi

PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" # for macos use realpath command

bindkey -s "^G" "lazygit\n"

# export PATH="/usr/local/opt/icu4c/bin:$PATH"
# export PATH="/usr/local/opt/icu4c/sbin:$PATH"
#
# stty eof undef  # prevent C-d to close panel

# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

source /usr/share/nvm/init-nvm.sh
